const metricNames = {
    "enrollment": "Enrollment",
    "survey_pp_ri": "Parent-Teacher Relationship Index",
    "survey_pp_ct": "Collaborative Teachers",
    "survey_pp_se": "Supportive Environment",
    "survey_pp_es": "Effective School Leadership",
    "survey_pp_sf": "Strong Family-Community Ties",
    "survey_pp_tr": "Trust",
    "gender_female_pct": "Percentage of Female Students",
    "gender_male_pct": "Percentage of Male Students",
    "ell": "English Language Learners",
    "iep": "Individualized Education Program",
    "cap_setss_pct": "Percentage of SETSS (Special Education Teacher Support Services)",
    "cap_ctt_pct": "Percentage of CTT (Collaborative Team Teaching)",
    "cap_sc_pct": "Percentage of Self-Contained Classes",
    "eni_hs_pct_912": "Economic Need Index (High School 9-12)",
    "hs_overage_undercredit_hoi": "High School Overage Undercredit HOI Percentage",
    "temp_housing_pct": "Percentage of Students in Temporary Housing",
    "hra_elig_pct": "Percentage of Students Eligible for HRA",
    "ethnicity_asian_pct": "Percentage of Asian Students",
    "ethnicity_black_pct": "Percentage of Black Students",
    "ethnicity_hispanic_pct": "Percentage of Hispanic Students",
    "ethnicity_amerindian_pct": "Percentage of American Indian Students",
    "ethnicity_pacific_pct": "Percentage of Pacific Islander Students",
    "ethnicity_white_pct": "Percentage of White Students",
    "teacher_ethnicity_asian_pct": "Percentage of Asian Teachers",
    "teacher_ethnicity_black_pct": "Percentage of Black Teachers",
    "teacher_ethnicity_hispanic": "Percentage of Hispanic Teachers",
    "teacher_ethnicity_amerindian": "Percentage of American Indian Teachers",
    "teacher_ethnicity_pacific": "Percentage of Pacific Islander Teachers",
    "teacher_ethnicity_white_pct": "Percentage of White Teachers",
    "median_distance": "Median Distance",
    "near_pct_asian": "Nearby Percentage of Asian Students",
    "near_pct_black": "Nearby Percentage of Black Students",
    "near_pct_hispanic": "Nearby Percentage of Hispanic Students",
    "near_pct_amerindian": "Nearby Percentage of American Indian Students",
    "near_pct_pacific": "Nearby Percentage of Pacific Islander Students",
    "near_pct_white": "Nearby Percentage of White Students",
    "ethnicity_asian_pct_boro": "Percentage of Asian Students (Borough)",
    "ethnicity_black_pct_boro": "Percentage of Black Students (Borough)",
    "ethnicity_hispanic_pct_boro": "Percentage of Hispanic Students (Borough)",
    "ethnicity_amerindian_pct_1": "Percentage of American Indian Students (Borough)",
    "ethnicity_pacific_pct_boro": "Percentage of Pacific Islander Students (Borough)",
    "ethnicity_white_pct_boro": "Percentage of White Students (Borough)",
    "pct_advanced_enroll_ea": "Percentage of Advanced Enrollment (EA)",
    "pct_advanced_enroll_eb": "Percentage of Advanced Enrollment (EB)",
    "pct_advanced_enroll_eh": "Percentage of Advanced Enrollment (EH)",
    "pct_advanced_enroll_ei": "Percentage of Advanced Enrollment (EI)",
    "pct_advanced_enroll_ep": "Percentage of Advanced Enrollment (EP)",
    "pct_advanced_enroll_ew": "Percentage of Advanced Enrollment (EW)",
    "pct_apib_enroll_ea": "Percentage of AP/IB Enrollment (EA)",
    "pct_apib_enroll_eb": "Percentage of AP/IB Enrollment (EB)",
    "pct_apib_enroll_eh": "Percentage of AP/IB Enrollment (EH)",
    "pct_apib_enroll_ei": "Percentage of AP/IB Enrollment (EI)",
    "pct_apib_enroll_ep": "Percentage of AP/IB Enrollment (EP)",
    "pct_apib_enroll_ew": "Percentage of AP/IB Enrollment (EW)",
    "principal_experience": "Principal Experience",
    "teach_3_more_exp": "Teachers with 3 or More Years of Experience",
    "val_attendance_hs_all": "Overall High School Attendance Rate",
    "val_chronic_absent_hs_all": "Overall High School Chronic Absenteeism Rate",
    "teacher_attendance": "Teacher Attendance Rate",
    "pct_fully_receiving_swd": "Percentage of Students Fully Receiving Special Education Services",
    "pct_partially_receiving_swd": "Percentage of Students Partially Receiving Special Education Services",
    "pct_not_receiving_swd": "Percentage of Students Not Receiving Special Education Services",
    "pct_fully_receiving_rs": "Percentage of Students Fully Receiving Related Services",
    "pct_partially_receiving_rs": "Percentage of Students Partially Receiving Related Services",
    "pct_not_receiving_rs": "Percentage of Students Not Receiving Related Services",
    "n_credit_10_pct_yr1": "Percentage of Students with 10+ Credits (Year 1)",
    "val_credit_10_pct_yr1": "Value of Students with 10+ Credits (Year 1)",
    "n_credit_10_pct_yr2": "Percentage of Students with 10+ Credits (Year 2)",
    "val_credit_10_pct_yr2": "Value of Students with 10+ Credits (Year 2)",
    "n_credit_10_pct_yr2_low_sc": "Percentage of Students with 10+ Credits (Year 2, Low Score)",
    "val_credit_10_pct_yr2_low": "Value of Students with 10+ Credits (Year 2, Low Score)",
    "n_credit_10_pct_yr3": "Percentage of Students with 10+ Credits (Year 3)",
    "val_credit_10_pct_yr3": "Value of Students with 10+ Credits (Year 3)",
    "n_credit_10_pct_yr3_low_sc": "Percentage of Students with 10+ Credits (Year 3, Low Score)",
    "val_credit_10_pct_yr3_low": "Value of Students with 10+ Credits (Year 3, Low Score)",
    "n_grad_pct_4_all": "Overall 4-Year Graduation Rate",
    "val_grad_pct_4_all": "Value of Overall 4-Year Graduation Rate",
    "n_grad_pct_6_all": "Overall 6-Year Graduation Rate",
    "val_grad_pct_6_all": "Value of Overall 6-Year Graduation Rate",
    "n_nondropout_4_all": "Overall 4-Year Non-Dropout Rate",
    "val_nondropout_4_all": "Value of Overall 4-Year Non-Dropout Rate",
    "n_nondropout_6_all": "Overall 6-Year Non-Dropout Rate",
    "val_nondropout_6_all": "Value of Overall 6-Year Non-Dropout Rate",
    "n_pct_cer_18mo_all": "Percentage of Students Earning College-Ready Credits (18 Months)",
    "val_pct_cer_18mo_all": "Value of Students Earning College-Ready Credits (18 Months)",
    "n_pct_cer_6mo_all": "Percentage of Students Earning College-Ready Credits (6 Months)",
    "val_pct_cer_6mo_all": "Value of Students Earning College-Ready Credits (6 Months)",
    "n_pct_cpci_all": "Percentage of Students Enrolled in Career and Technical Education (CTE)",
    "val_pct_cpci_all": "Value of Students Enrolled in Career and Technical Education (CTE)",
    "n_chronic_absent_hs_all": "Number of Chronically Absent High School Students",
    "n_lre_all": "Least Restrictive Environment (LRE)",
    "val_lre_all": "Value of Least Restrictive Environment (LRE)",
    "n_grad_pct_4_alleb": "4-Year Graduation Rate (English Learners Beginning)",
    "val_grad_pct_4_alleb": "Value of 4-Year Graduation Rate (English Learners Beginning)",
    "n_grad_pct_4_alleh": "4-Year Graduation Rate (English Learners High)",
    "val_grad_pct_4_alleh": "Value of 4-Year Graduation Rate (English Learners High)",
    "n_grad_pct_4_allei": "4-Year Graduation Rate (English Learners Intermediate)",
    "val_grad_pct_4_allei": "Value of 4-Year Graduation Rate (English Learners Intermediate)",
    "n_grad_pct_4_allep": "4-Year Graduation Rate (English Learners Proficient)",
    "n_grad_pct_4_bhl3_hs": "4-Year Graduation Rate (Low Socioeconomic Status)",
    "val_grad_pct_4_bhl3_hs": "Value of 4-Year Graduation Rate (Low Socioeconomic Status)",
    "n_grad_pct_4_cap5yr": "4-Year Graduation Rate (Special Education)",
    "val_grad_pct_4_cap5yr": "Value of 4-Year Graduation Rate (Special Education)",
    "n_grad_pct_4_ell5yr": "4-Year Graduation Rate (English Language Learners)",
    "val_grad_pct_4_ell5yr": "Value of 4-Year Graduation Rate (English Language Learners)",
    "n_grad_pct_4_l3c_hs": "4-Year Graduation Rate (Level 3 Courses)",
    "val_grad_pct_4_l3c_hs": "Value of 4-Year Graduation Rate (Level 3 Courses)",
    "n_pct_cer_6mo_l3c_hs": "6-Month College Enrollment Rate (Level 3 Courses)",
    "val_pct_cer_6mo_l3c_hs": "Value of 6-Month College Enrollment Rate (Level 3 Courses)",
    "n_pct_cpci_l3c_hs": "Percentage of Career and Technical Education (CTE) Participants (Level 3 Courses)",
    "val_pct_cpci_l3c_hs": "Value of Percentage of Career and Technical Education (CTE) Participants (Level 3 Courses)",
    "n_persist3_4yr_all": "4-Year College Persistence Rate",
    "val_persist3_4yr_all": "Value of 4-Year College Persistence Rate",
    "rr_s": "School Rating",
    "rr_t": "Teacher Rating",
    "rr_p": "Parent Rating",
    "n_attendance_hs_all": "High School Attendance Rate",
    "n_attendance_inperson_hs": "In-Person High School Attendance Rate",
    "val_attendance_inperson_hs": "Value of In-Person High School Attendance Rate",
    "n_attendance_remote_hs_all": "Remote High School Attendance Rate",
    "val_attendance_remote_hs": "Value of Remote High School Attendance Rate",
    "n_chronic_absent_hs_allea": "Chronic Absenteeism Rate (English A)",
    "val_chronic_absent_hs_allea": "Value of Chronic Absenteeism Rate (English A)",
    "n_chronic_absent_hs_alleb": "Chronic Absenteeism Rate (English B)",
    "val_chronic_absent_hs_alleb": "Value of Chronic Absenteeism Rate (English B)",
    "n_chronic_absent_hs_alleh": "Chronic Absenteeism Rate (History)",
    "val_chronic_absent_hs_alleh": "Value of Chronic Absenteeism Rate (History)",
    "n_chronic_absent_hs_allei": "Chronic Absenteeism Rate (International Baccalaureate)",
    "val_chronic_absent_hs_allei": "Value of Chronic Absenteeism Rate (International Baccalaureate)",
    "n_chronic_absent_hs_allem": "Chronic Absenteeism Rate (Mathematics)",
    "val_chronic_absent_hs_allem": "Value of Chronic Absenteeism Rate (Mathematics)",
    "n_chronic_absent_hs_allep": "Chronic Absenteeism Rate (Physical Education)",
    "val_chronic_absent_hs_allep": "Value of Chronic Absenteeism Rate (Physical Education)",
    "n_chronic_absent_hs_allew": "Chronic Absenteeism Rate (World Languages)",
    "val_chronic_absent_hs_allew": "Value of Chronic Absenteeism Rate (World Languages)",
    "n_chronic_absent_hs_allgf": "Chronic Absenteeism Rate (General Focus)",
    "val_chronic_absent_hs_allgf": "Value of Chronic Absenteeism Rate (General Focus)",
    "n_chronic_absent_hs_allgm": "Chronic Absenteeism Rate (General Mathematics)",
    "val_chronic_absent_hs_allgm": "Value of Chronic Absenteeism Rate (General Mathematics)",
    "n_cohort_pct_act_engl_all": "ACT English Proficiency Rate",
    "val_cohort_pct_act_engl_all": "Value of ACT English Proficiency Rate",
    "n_cohort_pct_act_math_all": "ACT Mathematics Proficiency Rate",
    "val_cohort_pct_act_math_all": "Value of ACT Mathematics Proficiency Rate",
    "n_cohort_pct_act_read_all": "ACT Reading Proficiency Rate",
    "val_cohort_pct_act_read_all": "Value of ACT Reading Proficiency Rate",
    "n_cohort_pct_act_scie_all": "ACT Science Proficiency Rate",
    "val_cohort_pct_act_scie_all": "Value of ACT Science Proficiency Rate",
    "n_credit_10_pct_yr1ea": "10+ Credits Earned Year 1 (English A)",
    "val_credit_10_pct_yr1ea": "Value of 10+ Credits Earned Year 1 (English A)",
    "n_credit_10_pct_yr1eb": "10+ Credits Earned Year 1 (English B)",
    "val_credit_10_pct_yr1eb": "Value of 10+ Credits Earned Year 1 (English B)",
    "n_credit_10_pct_yr1eh": "10+ Credits Earned Year 1 (History)",
    "val_credit_10_pct_yr1eh": "Value of 10+ Credits Earned Year 1 (History)",
    "n_credit_10_pct_yr1ei": "10+ Credits Earned Year 1 (International Baccalaureate)",
    "val_credit_10_pct_yr1ei": "Value of 10+ Credits Earned Year 1 (International Baccalaureate)",
    "n_credit_10_pct_yr1em": "10+ Credits Earned Year 1 (Mathematics)",
    "val_credit_10_pct_yr1em": "Value of 10+ Credits Earned Year 1 (Mathematics)",
    "n_credit_10_pct_yr1ep": "10+ Credits Earned Year 1 (Physical Education)",
    "n_credit_10_pct_yr1ew": "10+ Credits Earned Year 1 (World Languages)",
    "val_credit_10_pct_yr1ew": "Value of 10+ Credits Earned Year 1 (World Languages)",
    "n_credit_10_pct_yr1gf": "10+ Credits Earned Year 1 (General Focus)",
    "val_credit_10_pct_yr1gf": "Value of 10+ Credits Earned Year 1 (General Focus)",
    "n_credit_10_pct_yr1gm": "10+ Credits Earned Year 1 (General Mathematics)",
    "val_credit_10_pct_yr1gm": "Value of 10+ Credits Earned Year 1 (General Mathematics)",
    "n_credit_10_pct_yr2ea": "10+ Credits Earned Year 2 (English A)",
    "val_credit_10_pct_yr2ea": "Value of 10+ Credits Earned Year 2 (English A)",
    "n_credit_10_pct_yr2eb": "10+ Credits Earned Year 2 (English B)",
    "val_credit_10_pct_yr2eb": "Value of 10+ Credits Earned Year 2 (English B)",
    "n_credit_10_pct_yr2eh": "10+ Credits Earned Year 2 (History)",
    "val_credit_10_pct_yr2eh": "Value of 10+ Credits Earned Year 2 (History)",
    "n_credit_10_pct_yr2ei": "10+ Credits Earned Year 2 (International Baccalaureate)",
    "val_credit_10_pct_yr2ei": "Value of 10+ Credits Earned Year 2 (International Baccalaureate)",
    "n_credit_10_pct_yr2em": "10+ Credits Earned Year 2 (Mathematics)",
    "val_credit_10_pct_yr2em": "Value of 10+ Credits Earned Year 2 (Mathematics)",
    "n_credit_10_pct_yr2ep": "10+ Credits Earned Year 2 (Physical Education)",
    "n_credit_10_pct_yr2ew": "10+ Credits Earned Year 2 (World Languages)",
    "val_credit_10_pct_yr2ew": "Value of 10+ Credits Earned Year 2 (World Languages)",
    "n_credit_10_pct_yr2gf": "10+ Credits Earned Year 2 (General Focus)",
    "val_credit_10_pct_yr2gf": "Value of 10+ Credits Earned Year 2 (General Focus)",
    "n_credit_10_pct_yr2gm": "10+ Credits Earned Year 2 (General Mathematics)",
    "val_credit_10_pct_yr2gm": "Value of 10+ Credits Earned Year 2 (General Mathematics)",
    "n_credit_10_pct_yr3ea": "10+ Credits Earned Year 3 (English A)",
    "val_credit_10_pct_yr3ea": "Value of 10+ Credits Earned Year 3 (English A)",
    "n_credit_10_pct_yr3eb": "10+ Credits Earned Year 3 (English B)",
    "val_credit_10_pct_yr3eb": "Value of 10+ Credits Earned Year 3 (English B)",
    "n_credit_10_pct_yr3eh": "10+ Credits Earned Year 3 (History)",
    "val_credit_10_pct_yr3eh": "Value of 10+ Credits Earned Year 3 (History)",
    "n_credit_10_pct_yr3ei": "10+ Credits Earned Year 3 (International Baccalaureate)",
    "val_credit_10_pct_yr3ei": "Value of 10+ Credits Earned Year 3 (International Baccalaureate)",
    "n_credit_10_pct_yr3em": "10+ Credits Earned Year 3 (Mathematics)",
    "val_credit_10_pct_yr3em": "Value of 10+ Credits Earned Year 3 (Mathematics)",
    "n_credit_10_pct_yr3ep": "10+ Credits Earned Year 3 (Physical Education)",
    "val_credit_10_pct_yr3ep": "Value of 10+ Credits Earned Year 3 (Physical Education)",
    "n_credit_10_pct_yr3ew": "10+ Credits Earned Year 3 (World Languages)",
    "val_credit_10_pct_yr3ew": "Value of 10+ Credits Earned Year 3 (World Languages)",
    "n_credit_10_pct_yr3gf": "10+ Credits Earned Year 3 (General Focus)",
    "val_credit_10_pct_yr3gf": "Value of 10+ Credits Earned Year 3 (General Focus)",
    "n_credit_10_pct_yr3gm": "10+ Credits Earned Year 3 (General Mathematics)",
    "val_credit_10_pct_yr3gm": "Value of 10+ Credits Earned Year 3 (General Mathematics)",
    "n_grad_pct_4_allea": "4-Year Graduation Rate (English A)",
    "val_grad_pct_4_allea": "Value of 4-Year Graduation Rate (English A)",
    "n_grad_pct_4_allem": "4-Year Graduation Rate (Mathematics)",
    "val_grad_pct_4_allem": "Value of 4-Year Graduation Rate (Mathematics)",
    "n_grad_pct_4_allew": "4-Year Graduation Rate (World Languages)",
    "val_grad_pct_4_allew": "Value of 4-Year Graduation Rate (World Languages)",
    "n_grad_pct_4_allgf": "4-Year Graduation Rate (General Focus)",
    "val_grad_pct_4_allgf": "Value of 4-Year Graduation Rate (General Focus)",
    "n_grad_pct_4_allgm": "4-Year Graduation Rate (General Mathematics)",
    "val_grad_pct_4_allgm": "Value of 4-Year Graduation Rate (General Mathematics)",
    "n_grad_pct_4_nonnysaa_all": "4-Year Graduation Rate (Non-NYSAA Students)",
    "val_grad_pct_4_nonnysaa_all": "Value of 4-Year Graduation Rate (Non-NYSAA Students)",
    "n_grad_pct_6_allea": "6-Year Graduation Rate (English A)",
    "val_grad_pct_6_allea": "Value of 6-Year Graduation Rate (English A)",
    "n_grad_pct_6_alleb": "6-Year Graduation Rate (English B)",
    "val_grad_pct_6_alleb": "Value of 6-Year Graduation Rate (English B)",
    "n_grad_pct_6_alleh": "6-Year Graduation Rate (History)",
    "val_grad_pct_6_alleh": "Value of 6-Year Graduation Rate (History)",
    "n_grad_pct_6_allei": "6-Year Graduation Rate (International Baccalaureate)",
    "val_grad_pct_6_allei": "Value of 6-Year Graduation Rate (International Baccalaureate)",
    "n_grad_pct_6_allem": "6-Year Graduation Rate (Mathematics)",
    "val_grad_pct_6_allem": "Value of 6-Year Graduation Rate (Mathematics)",
    "n_grad_pct_6_allep": "6-Year Graduation Rate (Physical Education)",
    "val_grad_pct_6_allep": "Value of 6-Year Graduation Rate (Physical Education)",
    "n_grad_pct_6_allew": "6-Year Graduation Rate (World Languages)",
    "val_grad_pct_6_allew": "Value of 6-Year Graduation Rate (World Languages)",
    "n_grad_pct_6_allgf": "6-Year Graduation Rate (General Focus)",
    "val_grad_pct_6_allgf": "Value of 6-Year Graduation Rate (General Focus)",
    "n_grad_pct_6_allgm": "6-Year Graduation Rate (General Mathematics)",
    "val_grad_pct_6_allgm": "Value of 6-Year Graduation Rate (General Mathematics)",
    "n_grad_pct_6_nonnysaa_all": "6-Year Graduation Rate (Non-NYSAA Students)",
    "val_grad_pct_6_nonnysaa_all": "Value of 6-Year Graduation Rate (Non-NYSAA Students)",
    "n_grad_pct_watn8_level1": "Graduation Rate at NYS Level 1",
    "val_grad_pct_watn8_level1": "Value of Graduation Rate at NYS Level 1",
    "n_grad_pct_watn8_level2": "Graduation Rate at NYS Level 2",
    "val_grad_pct_watn8_level2": "Value of Graduation Rate at NYS Level 2",
    "n_grad_pct_watn8_level34": "Graduation Rate at NYS Level 3 and 4",
    "val_grad_pct_watn8_level34": "Value of Graduation Rate at NYS Level 3 and 4",
    "n_mean_score_act_engl_all": "Mean ACT Score (English)",
    "val_mean_score_act_engl_all": "Value of Mean ACT Score (English)",
    "n_mean_score_act_math_all": "Mean ACT Score (Mathematics)",
    "val_mean_score_act_math_all": "Value of Mean ACT Score (Mathematics)",
    "n_mean_score_act_read_all": "Mean ACT Score (Reading)",
    "val_mean_score_act_read_all": "Value of Mean ACT Score (Reading)",
    "n_mean_score_act_scie_all": "Mean ACT Score (Science)",
    "val_mean_score_act_scie_all": "Value of Mean ACT Score (Science)",
    "n_mean_score_sat_math_all": "Mean SAT Score (Mathematics)",
    "val_mean_score_sat_math_all": "Value of Mean SAT Score (Mathematics)",
    "n_mean_score_sat_writ_all": "Mean SAT Score (Writing)",
    "val_mean_score_sat_writ_all": "Value of Mean SAT Score (Writing)",
    "n_nondropout_4_allea": "4-Year Non-Dropout Rate (English A)",
    "val_nondropout_4_allea": "Value of 4-Year Non-Dropout Rate (English A)",
    "n_nondropout_4_alleb": "4-Year Non-Dropout Rate (English B)",
    "val_nondropout_4_alleb": "Value of 4-Year Non-Dropout Rate (English B)",
    "n_nondropout_4_alleh": "4-Year Non-Dropout Rate (History)",
    "val_nondropout_4_alleh": "Value of 4-Year Non-Dropout Rate (History)",
    "n_nondropout_4_allei": "4-Year Non-Dropout Rate (International Baccalaureate)",
    "val_nondropout_4_allei": "Value of 4-Year Non-Dropout Rate (International Baccalaureate)",
    "n_nondropout_4_allem": "4-Year Non-Dropout Rate (Mathematics)",
    "val_nondropout_4_allem": "Value of 4-Year Non-Dropout Rate (Mathematics)",
    "n_nondropout_4_allep": "4-Year Non-Dropout Rate (Physical Education)",
    "n_nondropout_4_allew": "4-Year Non-Dropout Rate (World Languages)",
    "val_nondropout_4_allew": "Value of 4-Year Non-Dropout Rate (World Languages)",
    "n_nondropout_4_allgf": "4-Year Non-Dropout Rate (General Focus)",
    "val_nondropout_4_allgf": "Value of 4-Year Non-Dropout Rate (General Focus)",
    "n_nondropout_4_allgm": "4-Year Non-Dropout Rate (General Mathematics)",
    "val_nondropout_4_allgm": "Value of 4-Year Non-Dropout Rate (General Mathematics)",
    "n_nondropout_6_allea": "6-Year Non-Dropout Rate (English A)",
    "val_nondropout_6_allea": "Value of 6-Year Non-Dropout Rate (English A)",
    "n_nondropout_6_alleb": "6-Year Non-Dropout Rate (English B)",
    "val_nondropout_6_alleb": "Value of 6-Year Non-Dropout Rate (English B)",
    "n_nondropout_6_alleh": "6-Year Non-Dropout Rate (History)",
    "val_nondropout_6_alleh": "Value of 6-Year Non-Dropout Rate (History)",
    "n_nondropout_6_allei": "6-Year Non-Dropout Rate (International Baccalaureate)",
    "val_nondropout_6_allei": "Value of 6-Year Non-Dropout Rate (International Baccalaureate)",
    "n_nondropout_6_allem": "6-Year Non-Dropout Rate (Mathematics)",
    "val_nondropout_6_allem": "Value of 6-Year Non-Dropout Rate (Mathematics)",
    "n_nondropout_6_allep": "6-Year Non-Dropout Rate (Physical Education)",
    "val_nondropout_6_allep": "Value of 6-Year Non-Dropout Rate (Physical Education)",
    "n_nondropout_6_allew": "6-Year Non-Dropout Rate (World Languages)",
    "val_nondropout_6_allew": "Value of 6-Year Non-Dropout Rate (World Languages)",
    "n_nondropout_6_allgf": "6-Year Non-Dropout Rate (General Focus)",
    "val_nondropout_6_allgf": "Value of 6-Year Non-Dropout Rate (General Focus)",
    "n_nondropout_6_allgm": "6-Year Non-Dropout Rate (General Mathematics)",
    "val_nondropout_6_allgm": "Value of 6-Year Non-Dropout Rate (General Mathematics)",
    "n_pct_cer_18mo_coll_2yr_all": "18-Month College Enrollment Rate (2-Year Colleges)",
    "val_pct_cer_18mo_coll_2yr": "Value of 18-Month College Enrollment Rate (2-Year Colleges)",
    "n_pct_cer_18mo_coll_4yr_all": "18-Month College Enrollment Rate (4-Year Colleges)",
    "val_pct_cer_18mo_coll_4yr": "Value of 18-Month College Enrollment Rate (4-Year Colleges)",
    "n_pct_cer_18mo_coll_oost": "18-Month College Enrollment Rate (Out of State)",
    "val_pct_cer_18mo_coll_oost": "Value of 18-Month College Enrollment Rate (Out of State)",
    "n_pct_cer_18mo_coll_priv": "18-Month College Enrollment Rate (Private Colleges)",
    "val_pct_cer_18mo_coll_priv": "Value of 18-Month College Enrollment Rate (Private Colleges)",
    "n_pct_cer_18mo_coll_publ": "18-Month College Enrollment Rate (Public Colleges)",
    "val_pct_cer_18mo_coll_publ": "Value of 18-Month College Enrollment Rate (Public Colleges)",
    "n_pct_cer_18mo_pub_svc_all": "18-Month Public Service Rate",
    "val_pct_cer_18mo_pub_svc": "Value of 18-Month Public Service Rate",
    "n_pct_cer_18mo_vocat_all": "18-Month Vocational School Enrollment Rate",
    "val_pct_cer_18mo_vocat_all": "Value of 18-Month Vocational School Enrollment Rate",
    "n_pct_cer_6mo_allea": "6-Month College Enrollment Rate (English A)",
    "val_pct_cer_6mo_allea": "Value of 6-Month College Enrollment Rate (English A)",
    "n_pct_cer_6mo_alleb": "6-Month College Enrollment Rate (English B)",
    "val_pct_cer_6mo_alleb": "Value of 6-Month College Enrollment Rate (English B)",
    "n_pct_cer_6mo_alleh": "6-Month College Enrollment Rate (History)",
    "val_pct_cer_6mo_alleh": "Value of 6-Month College Enrollment Rate (History)",
    "n_pct_cer_6mo_allei": "6-Month College Enrollment Rate (International Baccalaureate)",
    "val_pct_cer_6mo_allei": "Value of 6-Month College Enrollment Rate (International Baccalaureate)",
    "n_pct_cer_6mo_allem": "6-Month College Enrollment Rate (Mathematics)",
    "val_pct_cer_6mo_allem": "Value of 6-Month College Enrollment Rate (Mathematics)",
    "n_pct_cer_6mo_allep": "6-Month College Enrollment Rate (Physical Education)",
    "val_pct_cer_6mo_allep": "Value of 6-Month College Enrollment Rate (Physical Education)",
    "n_pct_cer_6mo_allew": "6-Month College Enrollment Rate (World Languages)",
    "val_pct_cer_6mo_allew": "Value of 6-Month College Enrollment Rate (World Languages)",
    "n_pct_cer_6mo_allgf": "6-Month College Enrollment Rate (General Focus)",
    "val_pct_cer_6mo_allgf": "Value of 6-Month College Enrollment Rate (General Focus)",
    "n_pct_cer_6mo_allgm": "6-Month College Enrollment Rate (General Mathematics)",
    "val_pct_cer_6mo_allgm": "Value of 6-Month College Enrollment Rate (General Mathematics)",
    "n_pct_cer_6mo_coll_2yr_all": "6-Month College Enrollment Rate (2-Year Colleges)",
    "val_pct_cer_6mo_coll_2yr": "Value of 6-Month College Enrollment Rate (2-Year Colleges)",
    "n_pct_cer_6mo_coll_4yr_all": "6-Month College Enrollment Rate (4-Year Colleges)",
    "val_pct_cer_6mo_coll_4yr": "Value of 6-Month College Enrollment Rate (4-Year Colleges)",
    "n_pct_cer_6mo_coll_oost_all": "6-Month College Enrollment Rate (Out of State)",
    "val_pct_cer_6mo_coll_oost": "Value of 6-Month College Enrollment Rate (Out of State)",
    "n_pct_cer_6mo_coll_priv_all": "6-Month College Enrollment Rate (Private Colleges)",
    "val_pct_cer_6mo_coll_priv": "Value of 6-Month College Enrollment Rate (Private Colleges)",
    "n_pct_cer_6mo_coll_publ_all": "6-Month College Enrollment Rate (Public Colleges)",
    "val_pct_cer_6mo_coll_publ": "Value of 6-Month College Enrollment Rate (Public Colleges)",
    "n_pct_cer_6mo_other_all": "6-Month Other Post-Secondary Enrollment Rate",
    "val_pct_cer_6mo_other_all": "Value of 6-Month Other Post-Secondary Enrollment Rate",
    "n_pct_cer_6mo_pub_svc_all": "6-Month Public Service Rate",
    "val_pct_cer_6mo_pub_svc_all": "Value of 6-Month Public Service Rate",
    "n_pct_cer_6mo_vocat_all": "6-Month Vocational School Enrollment Rate",
    "val_pct_cer_6mo_vocat_all": "Value of 6-Month Vocational School Enrollment Rate",
    "n_pct_clg_rdy_act_engl_all": "College Ready Rate (ACT English)",
    "val_pct_clg_rdy_act_engl": "Value of College Ready Rate (ACT English)",
    "n_pct_clg_rdy_act_math_all": "College Ready Rate (ACT Mathematics)",
    "val_pct_clg_rdy_act_math": "Value of College Ready Rate (ACT Mathematics)",
    "n_pct_clg_rdy_sat_math_all": "College Ready Rate (SAT Mathematics)",
    "val_pct_clg_rdy_sat_math": "Value of College Ready Rate (SAT Mathematics)",
    "n_pct_clg_rdy_sat_writ_all": "College Ready Rate (SAT Writing)",
    "val_pct_clg_rdy_sat_writ": "Value of College Ready Rate (SAT Writing)",
    "n_pct_cpci_allea": "Career and Technical Education (CTE) Participants (English A)",
    "val_pct_cpci_allea": "Value of Career and Technical Education (CTE) Participants (English A)",
    "n_pct_cpci_alleb": "Career and Technical Education (CTE) Participants (English B)",
    "val_pct_cpci_alleb": "Value of Career and Technical Education (CTE) Participants (English B)",
    "n_pct_cpci_alleh": "Career and Technical Education (CTE) Participants (History)",
    "val_pct_cpci_alleh": "Value of Career and Technical Education (CTE) Participants (History)",
    "n_pct_cpci_allei": "Career and Technical Education (CTE) Participants (International Baccalaureate)",
    "val_pct_cpci_allei": "Value of Career and Technical Education (CTE) Participants (International Baccalaureate)",
    "n_pct_cpci_allem": "Career and Technical Education (CTE) Participants (Mathematics)",
    "val_pct_cpci_allem": "Value of Career and Technical Education (CTE) Participants (Mathematics)",
    "n_pct_cpci_allep": "Career and Technical Education (CTE) Participants (Physical Education)",
    "n_pct_cpci_allew": "Career and Technical Education (CTE) Participants (World Languages)",
    "val_pct_cpci_allew": "Value of Career and Technical Education (CTE) Participants (World Languages)",
    "n_pct_cpci_allgf": "Career and Technical Education (CTE) Participants (General Focus)",
    "val_pct_cpci_allgf": "Value of Career and Technical Education (CTE) Participants (General Focus)",
    "n_pct_cpci_allgm": "Career and Technical Education (CTE) Participants (General Mathematics)",
    "val_pct_cpci_allgm": "Value of Career and Technical Education (CTE) Participants (General Mathematics)",
    "n_pct_cpci_ap_all": "Career and Technical Education (CTE) Participants (Advanced Placement)",
    "val_pct_cpci_ap_all": "Value of Career and Technical Education (CTE) Participants (Advanced Placement)",
    "n_pct_cpci_cpcc_all": "Career and Technical Education (CTE) Participants (College Preparatory Courses Completed)",
    "val_pct_cpci_cpcc_all": "Value of Career and Technical Education (CTE) Participants (College Preparatory Courses Completed)",
    "n_pct_cpci_cte_exam_all": "Career and Technical Education (CTE) Participants (CTE Exam)",
    "val_pct_cpci_cte_exam_all": "Value of Career and Technical Education (CTE) Participants (CTE Exam)",
    "n_pct_cpci_ib_all": "Career and Technical Education (CTE) Participants (International Baccalaureate)",
    "val_pct_cpci_ib_all": "Value of Career and Technical Education (CTE) Participants (International Baccalaureate)",
    "n_pct_cpci_other_college": "Career and Technical Education (CTE) Participants (Other College Level Courses)",
    "val_pct_cpci_other_college": "Value of Career and Technical Education (CTE) Participants (Other College Level Courses)",
    "n_pct_degree_arts_4yr_all": "4-Year Degree Rate (Arts)",
    "val_pct_degree_arts_4yr_all": "Value of 4-Year Degree Rate (Arts)",
    "n_pct_degree_cte_4yr_all": "4-Year Degree Rate (CTE)",
    "val_pct_degree_cte_4yr_all": "Value of 4-Year Degree Rate (CTE)",
    "n_pct_degree_reg_4yr_all": "4-Year Degree Rate (Regular)",
    "val_pct_degree_reg_4yr_all": "Value of 4-Year Degree Rate (Regular)",
    "n_pct_degree_reg_6yr_all": "6-Year Degree Rate (Regular)",
    "val_pct_degree_reg_6yr_all": "Value of 6-Year Degree Rate (Regular)"
  }
  
  
  
  

  